debug: false # logback debug 로그 레벨 설정
management.endpoints.web.exposure.include: "*" # actuator의 endPoint 중 감춰진 기능을 다 활성화

logging:
  level: # 구체적으로 명시하고 싶은 로그 레벨 설정
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace # JPA 기술을 사용할 때 쿼리 로그를 볼 때 파라미터를 볼 수 있도록 설정

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hwiBoard
    username: hwi
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # JPA 테스트 데이터베이스를 생성 및 테스트하도록 설정 (data.sql)
    hibernate.ddl-auto: create # 엔티티 및 각 JPA 관련 설정에 대한 DDL이 자동으로 실행
    show-sql: true # 로그에 sql 보여줄 것인지 설정
    properties:
      hibernate.format_sql: true # 디버그 쿼리 문을 포맷팅
      hibernate.default_batch_fetch_size: 100 # JPA에서 연관관계가 매핑이 되어 있는 쿼리를 호출할 때, 한 번에 select 문으로 변경하여 bulk select하도록 설정
  h2.console.enabled: true
  sql.init.mode: always #data.sql 을 실행할 시기에 대한 설정
  data.rest:
    base-path: /api
    detection-strategy: annotated # 프로젝트의 repository 중 rest api에 노출할 범위